Initial Release

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -69,6 +69,68 @@ jobs:
         run: |
           pytest tests -vv -rEPW -o pytest_collection_order=alphabetical --cache-clear --color=yes
 
+  test_ubuntu_gnome:
+    name: Test GNOME
+    timeout-minutes: 20
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ ubuntu-latest ]
+        python-version: [ '3.10', '3.11', '3.12' ]
+    runs-on: ${{ matrix.os }}
+    needs: lint
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pytest
+          pip install pytest-html
+          pip install -r requirements.txt
+
+      - name: Install GNOME Terminal
+        run: |
+          sudo apt update
+          sudo apt-get install -y at-spi2-core xvfb gnome-terminal dbus-x11
+
+      - name: Enable Display & Terminal Support
+        run: |
+          export TERM=gnome-terminal
+          export DISPLAY=:99.0
+          echo $TERM
+          export $(dbus-launch)
+
+      - name: Run Tests
+        run: |
+          xvfb-run dbus-launch gnome-terminal -- bash -c "pytest tests -vv -rEPW -o pytest_collection_order=alphabetical --cache-clear --color=yes --html=pytest_results.html --self-contained-html"
+
+      - name: Check For Failures
+        if: always()
+        run: |
+          failed_tests=$(grep -o '<span class="failed">\([0-9]\+\) Failed,</span>' pytest_results.html | sed 's/<[^>]*>//g' | awk '{print $1}')
+          echo $failed_tests
+          if [ "$failed_tests" -gt 0 ]; then
+            echo "There were $failed_tests failed test cases. Setting pipeline status to failed."
+            exit 1
+          else
+            echo "All tests passed. Setting pipeline status to success."
+            exit 0
+          fi
+
+      - name: Upload Report
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: ubuntu-gnome-${{ matrix.python-version }}
+          path: pytest_results.html
+
   build:
     name: Build
     timeout-minutes: 20
@@ -78,7 +140,7 @@ jobs:
         os: [ ubuntu-latest, windows-latest, macos-latest ]
         python-version: [ '3.10' ]
     runs-on: ${{ matrix.os }}
-    needs: test
+    needs: [ test, test_ubuntu_gnome ]
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
